assets: /home/navlab-aa290/tdeng/safe-robot-steering/LIBERO/libero/libero/./assets
bddl_files: /home/navlab-aa290/tdeng/safe-robot-steering/LIBERO/libero/libero/./bddl_files
benchmark_root: /home/navlab-aa290/tdeng/safe-robot-steering/LIBERO/libero/libero
datasets: /home/navlab-aa290/tdeng/safe-robot-steering/datset/datasets
init_states: /home/navlab-aa290/tdeng/safe-robot-steering/LIBERO/libero/libero/./init_files
